### ISSUE TITLE
Security warning when installing

### ISSUE THREAD

**Issue by ImOnALampshade** [betsegaw/windowwalker#67]
There's a security warning when installing Window Walker from the location linked in the README.

**Comment by bdoner** [comment]
Hi @betsegaw ,

I assume you have a reason to close this issue. But for some of us it means the application cannot be installed due to policies. Any workarounds?

![image](https://user-images.githubusercontent.com/2525536/73051860-fc22d300-3e83-11ea-9824-4589e4810a81.png)

**Comment by betsegaw** [comment]
Hey @bdoner, 

I am really sorry to hear that but this will soon not matter!

I was in the process of fixing this issue (setting up signing on my build machines) when I started working with the @crutkas and team to integrate this into PowerToys. Once that integration is complete, you will be able to use Window Walker from within PowerToys, which is signed and therefore, you won't run into the above security warning. 

In the mean time, you could clone this repository and build the app yourself to not run into the above issue (tedious, but again, very temporary).

Thanks,
Beta

**Comment by bdoner** [comment]
Awesome! Thanks for the response.
