### ISSUE TITLE
Fixed a crashing bug on WindowResultSelected in WindowWalkerViewModel

### ISSUE THREAD

**Issue by crutkas** [betsegaw/windowwalker#73]
I was getting a null error when i would delete the entire line then type something. this seemed to fix it.  This fix is in https://github.com/betsegaw/windowwalker/commit/44ab9c5ee5d5a4317d31b41a8a13d16cf7974579

private void WindowResultSelected()
        {
            **if (SelectedWindowResult != null)**
            {
                LivePreview.ActivateLivePreview(SelectedWindowResult.Result.Hwnd, Hwnd);
            }
        }

**Comment by betsegaw** [comment]
Interesting... I haven't been able to repro this but it doesn't hurt to have a null check on it in any case.
